package jp.monakaserver.monakabu.gui;

import jp.monakaserver.monakabu.config.ConfigManager;
import jp.monakaserver.monakabu.database.DatabaseManager;
import jp.monakaserver.monakabu.database.repository.SettlementRepository;
import jp.monakaserver.monakabu.database.repository.StatsRepository;
import jp.monakaserver.monakabu.market.MarketEventService;
import jp.monakaserver.monakabu.market.MarketService;
import jp.monakaserver.monakabu.market.StockRegistry;
import jp.monakaserver.monakabu.message.MessageService;
import jp.monakaserver.monakabu.model.PortfolioPosition;
import jp.monakaserver.monakabu.model.RankingEntry;
import jp.monakaserver.monakabu.model.Season;
import jp.monakaserver.monakabu.model.StockSnapshot;
import jp.monakaserver.monakabu.model.TradeResult;
import jp.monakaserver.monakabu.season.SeasonService;
import jp.monakaserver.monakabu.trading.TradingService;
import jp.monakaserver.monakabu.util.MainThread;
import jp.monakaserver.monakabu.util.Money;
import java.math.BigDecimal;
import java.time.Duration;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import net.kyori.adventure.text.Component;
import org.bukkit.Bukkit;
import org.bukkit.Material;
import org.bukkit.configuration.ConfigurationSection;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.inventory.InventoryClickEvent;
import org.bukkit.event.inventory.InventoryDragEvent;
import org.bukkit.inventory.Inventory;
import org.bukkit.inventory.ItemStack;
import org.bukkit.plugin.java.JavaPlugin;

public final class GuiService implements Listener {
    private static final int[] STOCK_SLOTS={10,11,12,13,14,15,16,19,20,21,22,23,24,25,28,29,30,31,32,33,34,37,38,39,40,41,42,43};
    private final JavaPlugin plugin;private final ConfigManager configs;private final StockRegistry stocks;private final TradingService trading;private final SeasonService seasons;
    private final MarketService market;private final MarketEventService events;private final DatabaseManager database;private final SettlementRepository rankings;private final StatsRepository stats;private final MessageService messages;
    public GuiService(JavaPlugin plugin,ConfigManager configs,StockRegistry stocks,TradingService trading,SeasonService seasons,MarketService market,MarketEventService events,DatabaseManager database,SettlementRepository rankings,StatsRepository stats,MessageService messages){this.plugin=plugin;this.configs=configs;this.stocks=stocks;this.trading=trading;this.seasons=seasons;this.market=market;this.events=events;this.database=database;this.rankings=rankings;this.stats=stats;this.messages=messages;}

    public void openMain(Player player){GuiHolder holder=inventory(GuiHolder.Menu.MAIN,"",0,configs.gui().getInt("main.size",45),title("main"));Inventory inv=holder.getInventory();ConfigurationSection root=configs.gui().getConfigurationSection("main");if(root!=null){setConfigured(holder,inv,root,"stocks",GuiHolder.Action.STOCKS);setConfigured(holder,inv,root,"portfolio",GuiHolder.Action.PORTFOLIO);setConfigured(holder,inv,root,"ranking",GuiHolder.Action.RANKING);setConfigured(holder,inv,root,"news",GuiHolder.Action.NEWS);setConfigured(holder,inv,root,"history",GuiHolder.Action.HISTORY);setConfigured(holder,inv,root,"close",GuiHolder.Action.CLOSE);ConfigurationSection filler=root.getConfigurationSection("filler");if(filler!=null){ItemStack item=configItem(filler);for(int i=0;i<inv.getSize();i++)if(inv.getItem(i)==null)inv.setItem(i,item);}}player.openInventory(inv);}

    public void openStocks(Player player,int page){trading.portfolio(player.getUniqueId()).thenAccept(positions->{Map<String,Long> owned=new HashMap<>();positions.forEach(p->owned.put(p.stockId(),p.shares()));MainThread.run(plugin,()->{List<StockSnapshot> list=new ArrayList<>(stocks.all());int maxPage=Math.max(0,(list.size()-1)/STOCK_SLOTS.length);int actual=Math.max(0,Math.min(page,maxPage));GuiHolder holder=inventory(GuiHolder.Menu.STOCKS,"",actual,54,title("stocks"));for(int i=0;i<STOCK_SLOTS.length;i++){int index=actual*STOCK_SLOTS.length+i;if(index>=list.size())break;StockSnapshot stock=list.get(index);double change=stock.changePercent();String arrow=change>=0?"<green>▲ +":"<red>▼ ";List<String> lore=List.of("<gray>株価: <white>"+Money.format(stock.price())+" MONA",arrow+String.format(java.util.Locale.ROOT,"%.2f%%",change),"<gray>本日高値: <white>"+Money.format(stock.dailyHigh())+" MONA","<gray>本日安値: <white>"+Money.format(stock.dailyLow())+" MONA","<gray>保有: <white>"+owned.getOrDefault(stock.definition().id(),0L)+"株","","<yellow>クリックで取引");holder.getInventory().setItem(STOCK_SLOTS[i],ItemFactory.item(stock.definition().icon(),stock.definition().displayName()+" <dark_gray>["+stock.definition().symbol()+"]",lore,stock.definition().customModelData()));holder.action(STOCK_SLOTS[i],new GuiHolder.ClickAction(GuiHolder.Action.STOCK,stock.definition().id(),0));}nav(holder,actual,maxPage);player.openInventory(holder.getInventory());});}).exceptionally(error->{log(error);return null;});}

    public void openTrade(Player player,String stockId){StockSnapshot stock=stocks.find(stockId).orElse(null);if(stock==null)return;market.history(stockId,Duration.ofDays(7),48).thenAccept(history->trading.portfolio(player.getUniqueId()).thenAccept(positions->MainThread.run(plugin,()->{long owned=positions.stream().filter(p->p.stockId().equals(stockId)).mapToLong(PortfolioPosition::shares).findFirst().orElse(0);Component tradeTitle=messages.raw(configs.gui().getString("titles.trade","<gold>取引: <stock>").replace("<stock>",stock.definition().symbol()));GuiHolder holder=inventory(GuiHolder.Menu.TRADE,stockId,0,45,tradeTitle);Inventory inv=holder.getInventory();inv.setItem(22,ItemFactory.item(stock.definition().icon(),stock.definition().displayName(),List.of("<gray>現在株価: <white>"+Money.format(stock.price())+" MONA","<gray>保有: <white>"+owned+"株","<gray>7日チャート:","<aqua>"+ChartRenderer.render(history,32))));List<Integer> buySlots=configs.gui().getIntegerList("trade.buy-slots");List<Integer> buyAmounts=configs.gui().getIntegerList("trade.buy-amounts");for(int i=0;i<Math.min(buySlots.size(),buyAmounts.size());i++){int amount=buyAmounts.get(i),slot=buySlots.get(i);inv.setItem(slot,ItemFactory.item(Material.LIME_CONCRETE,"<green>"+(amount<0?"最大":amount+"株")+"購入",List.of("<gray>左クリックで購入")));holder.action(slot,new GuiHolder.ClickAction(GuiHolder.Action.BUY,stockId,amount));}List<Integer> sellSlots=configs.gui().getIntegerList("trade.sell-slots");List<Integer> sellAmounts=configs.gui().getIntegerList("trade.sell-amounts");for(int i=0;i<Math.min(sellSlots.size(),sellAmounts.size());i++){int amount=sellAmounts.get(i),slot=sellSlots.get(i);inv.setItem(slot,ItemFactory.item(Material.RED_CONCRETE,"<red>"+(amount<0?"全株":amount+"株")+"売却",List.of("<gray>左クリックで売却")));holder.action(slot,new GuiHolder.ClickAction(GuiHolder.Action.SELL,stockId,amount));}back(holder,40);player.openInventory(inv);}))).exceptionally(error->{log(error);return null;});}

    public void openPortfolio(Player player){trading.portfolio(player.getUniqueId()).thenAccept(positions->MainThread.run(plugin,()->{GuiHolder holder=inventory(GuiHolder.Menu.PORTFOLIO,"",0,54,title("portfolio"));int index=0;for(PortfolioPosition position:positions){if(index>=STOCK_SLOTS.length)break;StockSnapshot stock=stocks.find(position.stockId()).orElse(null);if(stock==null)continue;BigDecimal invested=position.costBasis(),value=stock.price().multiply(BigDecimal.valueOf(position.shares())),profit=value.subtract(invested);double rate=invested.signum()==0?0:profit.divide(invested,6,java.math.RoundingMode.HALF_UP).doubleValue()*100;holder.getInventory().setItem(STOCK_SLOTS[index],ItemFactory.item(stock.definition().icon(),stock.definition().displayName(),List.of("<gray>保有: <white>"+position.shares()+"株","<gray>平均取得価格: <white>"+Money.format(position.averageCost())+" MONA","<gray>現在株価: <white>"+Money.format(stock.price())+" MONA","<gray>投資額: <white>"+Money.format(invested)+" MONA","<gray>評価額: <white>"+Money.format(value)+" MONA",(profit.signum()>=0?"<green>":"<red>")+"損益: "+Money.format(profit)+" MONA ("+String.format(java.util.Locale.ROOT,"%.2f",rate)+"%)")));holder.action(STOCK_SLOTS[index++],new GuiHolder.ClickAction(GuiHolder.Action.STOCK,position.stockId(),0));}back(holder,49);player.openInventory(holder.getInventory());})).exceptionally(error->{log(error);return null;});}

    public void openRanking(Player player){Season season=seasons.current();if(season==null)return;database.read(c->season.status()==jp.monakaserver.monakabu.model.MarketStatus.CLOSED?rankings.ranking(c,season.id(),45):rankings.liveRanking(c,season.id(),45)).thenAccept(entries->MainThread.run(plugin,()->{GuiHolder holder=inventory(GuiHolder.Menu.RANKING,"",0,54,title("ranking"));int slot=0;for(RankingEntry entry:entries){if(slot>=45)break;Material material=entry.rank()==1?Material.GOLD_INGOT:entry.rank()==2?Material.IRON_INGOT:entry.rank()==3?Material.COPPER_INGOT:Material.PAPER;holder.getInventory().setItem(slot++,ItemFactory.item(material,"<gold>"+entry.rank()+"位 <white>"+entry.playerName(),List.of((entry.realizedProfit().signum()>=0?"<green>+":"<red>")+Money.format(entry.realizedProfit())+" MONA","<gray>取引回数: "+entry.trades())));}back(holder,49);player.openInventory(holder.getInventory());})).exceptionally(error->{log(error);return null;});}

    public void openNews(Player player){GuiHolder holder=inventory(GuiHolder.Menu.NEWS,"",0,54,title("news"));int slot=10;for(var event:events.activeEvents()){holder.getInventory().setItem(slot++,ItemFactory.item(Material.PAPER,"<gold>"+event.definition().name(),List.of("<gray>銘柄: <white>"+event.definition().stockId(),"<gray>効果: <white>x"+event.definition().modifier(),"<gray>終了: <white>"+DateTimeFormatter.ofPattern("MM/dd HH:mm").withZone(ZoneId.systemDefault()).format(event.endsAt()))));if(slot>=44)break;}back(holder,49);player.openInventory(holder.getInventory());}

    public void openHistory(Player player){database.read(c->stats.recentTransactions(c,player.getUniqueId(),45)).thenAccept(rows->MainThread.run(plugin,()->{GuiHolder holder=inventory(GuiHolder.Menu.HISTORY,"",0,54,title("history"));int slot=0;for(var row:rows){Material material=row.type().equals("BUY")?Material.LIME_DYE:Material.RED_DYE;holder.getInventory().setItem(slot++,ItemFactory.item(material,"<white>"+row.type()+" <gold>"+row.stockId(),List.of("<gray>"+row.shares()+"株 @ "+Money.format(row.price())+" MONA","<gray>合計: "+Money.format(row.net())+" MONA","<dark_gray>"+row.id(),"<dark_gray>"+row.status())));}back(holder,49);player.openInventory(holder.getInventory());})).exceptionally(error->{log(error);return null;});}

    public void openAdmin(Player player){GuiHolder holder=inventory(GuiHolder.Menu.ADMIN,"",0,45,messages.raw("<red>MonaKabu 管理"));adminItem(holder,10,Material.EMERALD,"<green>株価管理",GuiHolder.Action.ADMIN_PRICES,"<gray>銘柄一覧と現在価格");adminItem(holder,12,Material.WRITABLE_BOOK,"<yellow>企業管理",GuiHolder.Action.ADMIN_COMPANIES,"<gray>stocks.yml の案内");adminItem(holder,14,Material.PAPER,"<aqua>イベント管理",GuiHolder.Action.ADMIN_EVENTS,"<gray>発生中ニュース");adminItem(holder,16,Material.REDSTONE_TORCH,"<red>市場停止",GuiHolder.Action.ADMIN_MARKET,"<gray>halt/resume の案内");adminItem(holder,28,Material.CLOCK,"<gold>シーズン管理",GuiHolder.Action.ADMIN_END,"<red>終了確認画面へ");adminItem(holder,30,Material.GOLD_BLOCK,"<gold>経済統計",GuiHolder.Action.ADMIN_ECONOMY,"<gray>今シーズンの集計");adminItem(holder,32,Material.CHEST,"<yellow>プレイヤー保有株",GuiHolder.Action.ADMIN_PORTFOLIO,"<gray>照会コマンドの案内");adminItem(holder,34,Material.GOLD_INGOT,"<gold>ランキング",GuiHolder.Action.ADMIN_RANKING,"<gray>現在ランキング");adminItem(holder,40,Material.BOOK,"<light_purple>取引履歴",GuiHolder.Action.ADMIN_HISTORY,"<gray>自分の取引履歴");player.openInventory(holder.getInventory());}
    private void openConfirmEnd(Player player){GuiHolder holder=inventory(GuiHolder.Menu.CONFIRM_SEASON_END,"",0,27,messages.raw("<red>本当にシーズンを終了しますか？"));holder.getInventory().setItem(11,ItemFactory.item(Material.LIME_CONCRETE,"<green>実行する",List.of("<red>この操作は取り消せません")));holder.action(11,new GuiHolder.ClickAction(GuiHolder.Action.CONFIRM_END,"",0));holder.getInventory().setItem(15,ItemFactory.item(Material.RED_CONCRETE,"<red>キャンセル",List.of()));holder.action(15,new GuiHolder.ClickAction(GuiHolder.Action.BACK,"",0));player.openInventory(holder.getInventory());}

    @EventHandler public void click(InventoryClickEvent event){if(!(event.getView().getTopInventory().getHolder() instanceof GuiHolder holder))return;event.setCancelled(true);if(!(event.getWhoClicked() instanceof Player player)||event.getRawSlot()<0||event.getRawSlot()>=event.getView().getTopInventory().getSize())return;GuiHolder.ClickAction action=holder.action(event.getRawSlot());if(action==null)return;switch(action.action()){
        case STOCKS->openStocks(player,0);case PORTFOLIO->openPortfolio(player);case RANKING->openRanking(player);case NEWS->openNews(player);case HISTORY->openHistory(player);case CLOSE->player.closeInventory();case STOCK->openTrade(player,action.value());case BUY->trade(player,true,action.value(),action.amount());case SELL->trade(player,false,action.value(),action.amount());case BACK->openMain(player);case PAGE->openStocks(player,(int)action.amount());case ADMIN_END->openConfirmEnd(player);case CONFIRM_END->{player.closeInventory();seasons.forceEnd();}case ADMIN_ECONOMY->{player.closeInventory();player.performCommand("monakabu economy");}case ADMIN_PRICES->openStocks(player,0);case ADMIN_COMPANIES->{player.closeInventory();player.sendMessage(messages.raw("<yellow>企業は plugins/MonaKabu/stocks.yml で編集し、/monakabu reload を実行してください。"));}case ADMIN_EVENTS->openNews(player);case ADMIN_MARKET->{player.closeInventory();player.sendMessage(messages.raw("<yellow>/monakabu halt <stock> [duration] または /monakabu resume <stock> を使用してください。"));}case ADMIN_PORTFOLIO->{player.closeInventory();player.sendMessage(messages.raw("<yellow>/monakabu portfolio <player> を使用してください。"));}case ADMIN_RANKING->openRanking(player);case ADMIN_HISTORY->openHistory(player);
    }}
    @EventHandler public void drag(InventoryDragEvent event){if(event.getView().getTopInventory().getHolder() instanceof GuiHolder)event.setCancelled(true);}

    private void trade(Player player,boolean buy,String stock,long amount){player.closeInventory();CompletableFutureAdapter.accept(buy?trading.buy(player,stock,amount):trading.sell(player,stock,amount),result->MainThread.run(plugin,()->{if(result.success())messages.send(player,buy?"buy-success":"sell-success",Map.of("stock",stock,"shares",Long.toString(result.shares()),"total",Money.format(result.net())));else messages.send(player,messageForReason(result.reason()));}));}
    private String messageForReason(String reason){return switch(reason){case "BUSY"->"busy";case "MARKET_CLOSED"->"market-closed";case "STOCK_HALTED"->"stock-halted";case "NOT_ENOUGH_SHARES"->"not-enough-shares";case "LIMIT_SHARES","LIMIT_INVESTMENT"->"limit-exceeded";case "NO_PERMISSION"->"no-permission";case "NOT_ENOUGH_MONEY"->"not-enough-money";default->"trade-failed";};}

    private GuiHolder inventory(GuiHolder.Menu menu,String context,int page,int size,Component title){GuiHolder holder=new GuiHolder(menu,context,page);Inventory inventory=Bukkit.createInventory(holder,size,title);holder.inventory(inventory);return holder;}
    private Component title(String key){return messages.raw(configs.gui().getString("titles."+key,key));}
    private void back(GuiHolder holder,int slot){holder.getInventory().setItem(slot,ItemFactory.item(Material.ARROW,"<yellow>戻る",List.of()));holder.action(slot,new GuiHolder.ClickAction(GuiHolder.Action.BACK,"",0));}
    private void nav(GuiHolder holder,int page,int max){back(holder,49);if(page>0){holder.getInventory().setItem(45,ItemFactory.item(Material.ARROW,"<yellow>前へ",List.of()));holder.action(45,new GuiHolder.ClickAction(GuiHolder.Action.PAGE,"",page-1));}if(page<max){holder.getInventory().setItem(53,ItemFactory.item(Material.ARROW,"<yellow>次へ",List.of()));holder.action(53,new GuiHolder.ClickAction(GuiHolder.Action.PAGE,"",page+1));}}
    private void setConfigured(GuiHolder holder,Inventory inv,ConfigurationSection root,String key,GuiHolder.Action action){ConfigurationSection section=root.getConfigurationSection(key);if(section==null)return;int slot=section.getInt("slot");inv.setItem(slot,configItem(section));holder.action(slot,new GuiHolder.ClickAction(action,"",0));}
    private ItemStack configItem(ConfigurationSection section){Material material=Material.matchMaterial(section.getString("material","PAPER"));return ItemFactory.item(material==null?Material.PAPER:material,section.getString("name"," "),section.getStringList("lore"),section.getInt("custom-model-data",0));}
    private void adminItem(GuiHolder holder,int slot,Material material,String name,GuiHolder.Action action,String lore){holder.getInventory().setItem(slot,ItemFactory.item(material,name,List.of(lore)));holder.action(slot,new GuiHolder.ClickAction(action,"",0));}
    private void log(Throwable error){plugin.getLogger().log(Level.SEVERE,"GUI load failed",error);}

    private static final class CompletableFutureAdapter {static <T> void accept(java.util.concurrent.CompletableFuture<T> future,java.util.function.Consumer<T> consumer){future.thenAccept(consumer).exceptionally(error->{return null;});}}
}
